server:
  port: 8082
spring:
  application:
    name: feedback
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${URL_DB}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

resend:
  api:
    key: ${RESEND_API_KEY}
#Deepgram para transformcion de audios a feedaback textual

deepgram:
  api:
    key: ${DEEPGRAM_API_KEY}
    url: https://api.deepgram.com/v1/listen?model=nova-2&language=es

supabase:
  bucket:
    access-key: ${SB_BUCKET_ACCESS_KEY_ID}
    secret-key: ${SB_BUCKET_SECRET_ACCESS_KEY}
    endpoint: ${SB_BUCKET_ENDPOINT}
    region: ${SB_BUCKET_REGION}
    name: avatars
web:
  origin: ${URL_ORIGIN}